name = "ConvexTests"
uuid = "cb7cb77b-aa64-41ee-9be8-cb42f39823db"
authors = ["Eric <5846501+ericphanson@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateBases = "be282fd4-ad43-11e9-1d11-8bd9d7e43378"
MultivariateMoments = "f4abf1af-0426-5881-a0da-e2f168889b5e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"
TableTestSets = "f9bf3ced-5811-49c3-be57-f5a2c1e23f47"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
Convex = "0.13"
SumOfSquares = "0.4.1"
